<div id='about_container' class='content_container'>
<h2 class='content'>About</h2>
<p class='content'>
Jules Vano Inc. is a PR/Marketing business that was started in the summer of 2008 to promote events in the SF nightlife and entertainment industry. Within one year, the company founder Jules Vano
 became a highly demanded promoter with a strong and dedicated following. 
</p>
<p>
She used her public relations skills and professionalism to gain notoriety and respect from top San Francisco club owners, veteran promoters as well as San Francisco Bay Area industry icons--DJ Romeo, DJ Eroc, DJ Rick Lee, etc.
</p>
<p>
Today, Jules Vano Inc. has expanded into promotion and marketing services for products, private events, and political campaigns. She is currently working on a campaign fundraiser for Kamala Harris, San Francisco’s District Attorney running for California Attorney General for 2010.
</p>
<br/>
<br/>
</div>
