<div id='main'>
  <div id='nav'>
    <div id='menu'> 
      <span id='home' class='menu_item'><a id='home_link' href="#" >HOME</a></span>
      <span class='menu_separator'>|</span> 
      <span id='clients' class='menu_item'><a id='clients_link' href="#" >CLIENTS</a></span>
      <span class='menu_separator'>|</span>
      <span id='events' class='menu_item'><a id='events_link' href='#'>EVENTS</a></span>
      <span class='menu_separator'>|</span>
      <span id='contact' class='menu_item'><a id='contact_link' href='#'>CONTACT</a></span>
      <span class='menu_separator'>|</span>
      <span id='about' class='menu_item'><a id='about' href='#'>ABOUT</a></span>
    </div>
  </div>
 <div id='main_body'>
   <div id='image_container'>
   <img src='images/image01.jpg' width='310px' height='310px'/>
   </div>
   <div id='body_text' style='visibility: hidden;'>
    body text
   </div>
 </div>
</div>

